# Generated by Django 5.2.1 on 2025-05-21 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qatagonlarclassmodel',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
